services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-db
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=test$1245
      - POSTGRES_USER=kornnisa
      - POSTGRES_DB=kornnisa

  admin:
    image: dpage/pgadmin4:latest
    container_name: 69-s2-admin
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=test$1245
      
    
